### ISSUE TITLE
座標に負の数を入力できてしまう

### ISSUE THREAD

**Issue by claustra01** [simesaba80/othello#10]
横に負の数を入力すると配列のメモリを参照して配列内であれば石を配置できてしまう．
メモリが配列の外を参照しておりハンドリングされていなかった場合は石を置けないにも関わらず手番が変わってしまう．
<img width="836" alt="タイトルなし" src="https://github.com/simesaba80/othello/assets/108509532/c3588ebe-c368-4cf5-b101-a663994c5e56">

**Comment by simesaba80** [comment]
範囲外や負の数、既に埋まっている場所を選ぶとcontinue文で処理しなおすようにしました

**Comment by simesaba80** [comment]
1を入力すると範囲外となっていたので修正しました
