### ISSUE TITLE
座標に整数以外も入力できてしまう

### ISSUE THREAD

**Issue by claustra01** [simesaba80/othello#11]
これは`scanf()`の仕様だから意地悪だけど頑張って対策してほしい
`fgets()`で文字列として読む→数字かどうか判定→文字を数字に変換
の流れでできると思う

**Comment by simesaba80** [comment]
fgets()で文字列として読みstrtol()で変換させ、2文字目までに数字以外の文字がある場合は再入力させるようにしました
